// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  http

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( BankHandler ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BankHandler ) UnmarshalJSON([]byte) error { return nil }
func ( BankHandler ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BankHandler ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BankHandler *BankHandler

func ( CreateBankRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateBankRequest ) UnmarshalJSON([]byte) error { return nil }
func ( CreateBankRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateBankRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateBankRequest *CreateBankRequest

func ( CreateBankResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateBankResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CreateBankResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateBankResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateBankResponse *CreateBankResponse
