// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"

	httputils "github.com/edgarSucre/crm/internal/infrastructure/thttp/httputils"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp(in *jlexer.Lexer, out *CreateClientRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "birthdate":
			if in.IsNull() {
				in.Skip()
				out.BirthDate = nil
			} else {
				if out.BirthDate == nil {
					out.BirthDate = new(httputils.Date)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.BirthDate).UnmarshalJSON(data))
					}
				}
			}
		case "country":
			if in.IsNull() {
				in.Skip()
				out.Country = nil
			} else {
				if out.Country == nil {
					out.Country = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Country = string(in.String())
				}
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp(out *jwriter.Writer, in CreateClientRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"birthdate\":"
		out.RawString(prefix[1:])
		if in.BirthDate == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.BirthDate).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		if in.Country == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Country))
		}
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateClientRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateClientRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateClientRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateClientRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp(l, v)
}
func easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp1(in *jlexer.Lexer, out *ClientResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "birthdate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BirthDate = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "full_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FullName = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp1(out *jwriter.Writer, in ClientResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"birthdate\":"
		out.RawString(prefix[1:])
		out.String(string(in.BirthDate))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"full_name\":"
		out.RawString(prefix)
		out.String(string(in.FullName))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ClientResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ClientResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ClientResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ClientResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp1(l, v)
}
func easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp2(in *jlexer.Lexer, out *ClientHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp2(out *jwriter.Writer, in ClientHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ClientHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ClientHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCe40ee54EncodeGithubComEdgarSucreCrmInternalInfrastructureThttp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ClientHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ClientHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCe40ee54DecodeGithubComEdgarSucreCrmInternalInfrastructureThttp2(l, v)
}
