// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2868b426DecodeGithubComEdgarSucreCrmInternalInfrastructureHttp(in *jlexer.Lexer, out *CreditResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bank_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BankID = string(in.String())
			}
		case "client_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClientID = string(in.String())
			}
		case "credit_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreditType = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "max_payment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxPayment = string(in.String())
			}
		case "min_payment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinPayment = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "term_months":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TermMonths = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2868b426EncodeGithubComEdgarSucreCrmInternalInfrastructureHttp(out *jwriter.Writer, in CreditResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bank_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.BankID))
	}
	{
		const prefix string = ",\"client_id\":"
		out.RawString(prefix)
		out.String(string(in.ClientID))
	}
	{
		const prefix string = ",\"credit_type\":"
		out.RawString(prefix)
		out.String(string(in.CreditType))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"max_payment\":"
		out.RawString(prefix)
		out.String(string(in.MaxPayment))
	}
	{
		const prefix string = ",\"min_payment\":"
		out.RawString(prefix)
		out.String(string(in.MinPayment))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"term_months\":"
		out.RawString(prefix)
		out.Int(int(in.TermMonths))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreditResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2868b426EncodeGithubComEdgarSucreCrmInternalInfrastructureHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreditResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2868b426EncodeGithubComEdgarSucreCrmInternalInfrastructureHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreditResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2868b426DecodeGithubComEdgarSucreCrmInternalInfrastructureHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreditResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2868b426DecodeGithubComEdgarSucreCrmInternalInfrastructureHttp(l, v)
}
func easyjson2868b426DecodeGithubComEdgarSucreCrmInternalInfrastructureHttp1(in *jlexer.Lexer, out *CreateCreditRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bank_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BankID = string(in.String())
			}
		case "client_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClientID = string(in.String())
			}
		case "credit_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreditType = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2868b426EncodeGithubComEdgarSucreCrmInternalInfrastructureHttp1(out *jwriter.Writer, in CreateCreditRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bank_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.BankID))
	}
	{
		const prefix string = ",\"client_id\":"
		out.RawString(prefix)
		out.String(string(in.ClientID))
	}
	{
		const prefix string = ",\"credit_type\":"
		out.RawString(prefix)
		out.String(string(in.CreditType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateCreditRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2868b426EncodeGithubComEdgarSucreCrmInternalInfrastructureHttp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateCreditRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2868b426EncodeGithubComEdgarSucreCrmInternalInfrastructureHttp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateCreditRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2868b426DecodeGithubComEdgarSucreCrmInternalInfrastructureHttp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateCreditRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2868b426DecodeGithubComEdgarSucreCrmInternalInfrastructureHttp1(l, v)
}
