// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package client

import (
	json "encoding/json"
	httputils "github.com/edgarSucre/crm/internal/infrastructure/http/httputils"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient(in *jlexer.Lexer, out *CreateClientResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "birthdate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BirthDate).UnmarshalJSON(data))
				}
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "full_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FullName = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient(out *jwriter.Writer, in CreateClientResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"birthdate\":"
		out.RawString(prefix[1:])
		out.Raw((in.BirthDate).MarshalJSON())
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"full_name\":"
		out.RawString(prefix)
		out.String(string(in.FullName))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.RawText((in.ID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateClientResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateClientResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateClientResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateClientResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient(l, v)
}
func easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient1(in *jlexer.Lexer, out *CreateClientRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "birthdate":
			if in.IsNull() {
				in.Skip()
				out.BirthDate = nil
			} else {
				if out.BirthDate == nil {
					out.BirthDate = new(httputils.Date)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.BirthDate).UnmarshalJSON(data))
					}
				}
			}
		case "country":
			if in.IsNull() {
				in.Skip()
				out.Country = nil
			} else {
				if out.Country == nil {
					out.Country = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Country = string(in.String())
				}
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FirstName = string(in.String())
			}
		case "last_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient1(out *jwriter.Writer, in CreateClientRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"birthdate\":"
		out.RawString(prefix[1:])
		if in.BirthDate == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.BirthDate).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		if in.Country == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Country))
		}
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateClientRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateClientRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateClientRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateClientRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpClient1(l, v)
}
