// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package credit

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDf5ac817DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(in *jlexer.Lexer, out *CreateCreditRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bank_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BankID = string(in.String())
			}
		case "client_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClientID = string(in.String())
			}
		case "credit_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreditType = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDf5ac817EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(out *jwriter.Writer, in CreateCreditRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bank_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.BankID))
	}
	{
		const prefix string = ",\"client_id\":"
		out.RawString(prefix)
		out.String(string(in.ClientID))
	}
	{
		const prefix string = ",\"credit_type\":"
		out.RawString(prefix)
		out.String(string(in.CreditType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateCreditRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDf5ac817EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateCreditRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDf5ac817EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateCreditRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDf5ac817DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateCreditRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDf5ac817DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(l, v)
}
