// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package credit

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF67c5b6dDecodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(in *jlexer.Lexer, out *GetCreditResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "bank_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.BankID).UnmarshalText(data))
				}
			}
		case "client_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ClientID).UnmarshalText(data))
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "credit_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreditType = string(in.String())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		case "max_payment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxPayment = string(in.String())
			}
		case "min_payment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinPayment = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "term_months":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TermMonths = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF67c5b6dEncodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(out *jwriter.Writer, in GetCreditResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bank_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.BankID).MarshalText())
	}
	{
		const prefix string = ",\"client_id\":"
		out.RawString(prefix)
		out.RawText((in.ClientID).MarshalText())
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"credit_type\":"
		out.RawString(prefix)
		out.String(string(in.CreditType))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"max_payment\":"
		out.RawString(prefix)
		out.String(string(in.MaxPayment))
	}
	{
		const prefix string = ",\"min_payment\":"
		out.RawString(prefix)
		out.String(string(in.MinPayment))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"term_months\":"
		out.RawString(prefix)
		out.Int(int(in.TermMonths))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetCreditResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF67c5b6dEncodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCreditResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF67c5b6dEncodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCreditResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF67c5b6dDecodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCreditResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF67c5b6dDecodeGithubComEdgarSucreCrmInternalInfrastructureHttpCredit(l, v)
}
