// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type BankType string

const (
	BankTypePrivate    BankType = "private"
	BankTypeGovernment BankType = "government"
)

func (e *BankType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BankType(s)
	case string:
		*e = BankType(s)
	default:
		return fmt.Errorf("unsupported scan type for BankType: %T", src)
	}
	return nil
}

type NullBankType struct {
	BankType BankType
	Valid    bool // Valid is true if BankType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBankType) Scan(value interface{}) error {
	if value == nil {
		ns.BankType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BankType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBankType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BankType), nil
}

type CreditStatus string

const (
	CreditStatusPending  CreditStatus = "pending"
	CreditStatusApproved CreditStatus = "approved"
	CreditStatusRejected CreditStatus = "rejected"
)

func (e *CreditStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditStatus(s)
	case string:
		*e = CreditStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditStatus: %T", src)
	}
	return nil
}

type NullCreditStatus struct {
	CreditStatus CreditStatus
	Valid        bool // Valid is true if CreditStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CreditStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditStatus), nil
}

type CreditType string

const (
	CreditTypeAuto       CreditType = "auto"
	CreditTypeMortgage   CreditType = "mortgage"
	CreditTypeCommercial CreditType = "commercial"
)

func (e *CreditType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditType(s)
	case string:
		*e = CreditType(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditType: %T", src)
	}
	return nil
}

type NullCreditType struct {
	CreditType CreditType
	Valid      bool // Valid is true if CreditType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditType) Scan(value interface{}) error {
	if value == nil {
		ns.CreditType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditType), nil
}

type Bank struct {
	ID   uuid.UUID
	Name string
	Type BankType
}

type Client struct {
	ID        uuid.UUID
	FullName  string
	Email     string
	Birthdate time.Time
	Country   string
	CreatedAt time.Time
}

type Credit struct {
	ID         uuid.UUID
	ClientID   uuid.UUID
	BankID     uuid.UUID
	MinPayment decimal.Decimal
	MaxPayment decimal.Decimal
	TermMonths int16
	CreditType CreditType
	CreatedAt  time.Time
	Status     CreditStatus
}
