// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	GetClient(ctx context.Context, id uuid.UUID) (Client, error)
}

var _ Querier = (*Queries)(nil)
