// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createBank = `-- name: CreateBank :one
INSERT INTO banks (name, type) VALUES ($1, $2) RETURNING id, name, type
`

type CreateBankParams struct {
	Name string
	Type BankType
}

func (q *Queries) CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error) {
	row := q.db.QueryRow(ctx, createBank, arg.Name, arg.Type)
	var i Bank
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}

const getBank = `-- name: GetBank :one
SELECT id, name, type FROM banks
WHERE id = $1
`

func (q *Queries) GetBank(ctx context.Context, id uuid.UUID) (Bank, error) {
	row := q.db.QueryRow(ctx, getBank, id)
	var i Bank
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}
