// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    full_name, email, birthdate, country
) VALUES (
    $1, $2, $3, $4
) RETURNING id, full_name, email, birthdate, country, created_at
`

type CreateClientParams struct {
	FullName  string
	Email     string
	Birthdate *time.Time
	Country   *string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.FullName,
		arg.Email,
		arg.Birthdate,
		arg.Country,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Birthdate,
		&i.Country,
		&i.CreatedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, full_name, email, birthdate, country, created_at FROM clients
WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Birthdate,
		&i.Country,
		&i.CreatedAt,
	)
	return i, err
}
