// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createCredit = `-- name: CreateCredit :one
INSERT INTO credit (
    client_id, bank_id, min_payment, max_payment, term_months, credit_type, status
) VALUES (
   $1, $2, $3, $4, $5, $6, $7
) RETURNING id, client_id, bank_id, min_payment, max_payment, term_months, credit_type, created_at, status
`

type CreateCreditParams struct {
	ClientID   uuid.UUID
	BankID     uuid.UUID
	MinPayment decimal.Decimal
	MaxPayment decimal.Decimal
	TermMonths int16
	CreditType CreditType
	Status     CreditStatus
}

func (q *Queries) CreateCredit(ctx context.Context, arg CreateCreditParams) (Credit, error) {
	row := q.db.QueryRow(ctx, createCredit,
		arg.ClientID,
		arg.BankID,
		arg.MinPayment,
		arg.MaxPayment,
		arg.TermMonths,
		arg.CreditType,
		arg.Status,
	)
	var i Credit
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.BankID,
		&i.MinPayment,
		&i.MaxPayment,
		&i.TermMonths,
		&i.CreditType,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getClientCredits = `-- name: GetClientCredits :many
SELECT id, client_id, bank_id, min_payment, max_payment, term_months, credit_type, created_at, status FROM credit where client_id = $1
`

func (q *Queries) GetClientCredits(ctx context.Context, clientID uuid.UUID) ([]Credit, error) {
	rows, err := q.db.Query(ctx, getClientCredits, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credit
	for rows.Next() {
		var i Credit
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.BankID,
			&i.MinPayment,
			&i.MaxPayment,
			&i.TermMonths,
			&i.CreditType,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredit = `-- name: GetCredit :one
SELECT id, client_id, bank_id, min_payment, max_payment, term_months, credit_type, created_at, status FROM credit WHERE id = $1
`

func (q *Queries) GetCredit(ctx context.Context, id uuid.UUID) (Credit, error) {
	row := q.db.QueryRow(ctx, getCredit, id)
	var i Credit
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.BankID,
		&i.MinPayment,
		&i.MaxPayment,
		&i.TermMonths,
		&i.CreditType,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const updateCreditStatus = `-- name: UpdateCreditStatus :exec
UPDATE credit SET status = $1
`

func (q *Queries) UpdateCreditStatus(ctx context.Context, status CreditStatus) error {
	_, err := q.db.Exec(ctx, updateCreditStatus, status)
	return err
}
