// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBank(ctx context.Context, arg CreateBankParams) (Bank, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateCredit(ctx context.Context, arg CreateCreditParams) (Credit, error)
	GetBank(ctx context.Context, id uuid.UUID) (Bank, error)
	GetClient(ctx context.Context, id uuid.UUID) (Client, error)
	GetClientCredits(ctx context.Context, clientID uuid.UUID) ([]Credit, error)
	GetCredit(ctx context.Context, id uuid.UUID) (Credit, error)
	UpdateCreditStatus(ctx context.Context, arg UpdateCreditStatusParams) error
}

var _ Querier = (*Queries)(nil)
