// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package bank

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank(in *jlexer.Lexer, out *CreateBankResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank(out *jwriter.Writer, in CreateBankResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateBankResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateBankResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateBankResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateBankResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank(l, v)
}
func easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank1(in *jlexer.Lexer, out *CreateBankRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank1(out *jwriter.Writer, in CreateBankRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateBankRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateBankRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3a89b9d5EncodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateBankRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateBankRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3a89b9d5DecodeGithubComEdgarSucreCrmInternalInfrastructureHttpBank1(l, v)
}
